### ISSUE TITLE
Security: Upgrade django to version 2.1.2 or later

### ISSUE THREAD

**Issue by LordAlucard90** [LordAlucard90/Kanb.App#15]

**Comment by BugliL** [comment]
Updated requirements.txt added Django=2.1.4

**Comment by Wabri** [comment]
Potete usare i comandi github per chiudere gli issues o comunque fare riferimento all'issue che state risolvendo all'interno di un branch/PR: https://help.github.com/articles/closing-issues-using-keywords/

Solitamente si assegna al branch di sviluppo di una feature il numero dell'issue corrispondente che si risolve tipo **buglil-patch-15** oppure se volete essere più specifici anche così **buglil-patch-15-security-upgrade** per poi inserire nella descrizione della PR l'issue che state risolvendo per fare in modo che quando mergerete la PR l'issue si autochiuderà. Esempio:
![this](https://user-images.githubusercontent.com/12409541/50451164-ad2e0580-0932-11e9-8c1f-c01f958f86e9.png)

So che può essere ridondante ma quando si hanno intorno alle 10 PR attive con 100 issues è la svolta della vita avere riferimenti ovunque.
