### ISSUE TITLE
security warning variable

### ISSUE THREAD

**Issue by Wabri** [LordAlucard90/Kanb.App#19]
è normale che una variabile indicata come **SECURITY WARNING** sia resa pubblica?

https://github.com/AKGBs/Kanb.App-Server-Django/blob/4cd1bfa5ad4d58c1b594756437ce2970d19ee128/server/kanban_server/kanban_server/settings.py#L21
https://github.com/AKGBs/Kanb.App-Server-Django/blob/4cd1bfa5ad4d58c1b594756437ce2970d19ee128/server/kanban_server/kanban_server/settings.py#L22

**Comment by BugliL** [comment]
Si' basta cambiarla in fase di implementazione quando viene messa in produzione, per Django e' una pratica abbastanza normale fare in questo modo. Altrimenti avremmo dovuto scrivere quella, la password dell'utente del DB tutto in un file separato che dovevamo non committare. Piu' comodo scrivere la chiave in chiaro e cambiarla in fase di implementazione come e' scritto nel settings

**Comment by BugliL** [comment]
Allo stesso modo va corretto questo, che risulta un "buco" di sicurezza piu' grande
https://github.com/AKGBs/Kanb.App-Server-Django/blob/4cd1bfa5ad4d58c1b594756437ce2970d19ee128/server/kanban_server/kanban_server/settings.py#L24-L25
