### ISSUE TITLE
Duplicazione nomenclatura(?)

### ISSUE THREAD

**Issue by Wabri** [LordAlucard90/Kanb.App#20]
Forse sono io che ho problemi, ma è normale che il pacchetto kanban_server stia sotto kanban_server che sta sotto server? Secondo me aumenta i rischi di errore, modificare con **core** il pacchetto **kanban_server** più in profondità non sarebbe male, in questo modo c'è una distinzione tra il server effettivo che è il core e tutto ciò che ha bisogno il server per eseguire che è kanban_server. 

**server/kanban_server/kanban_server/** **->** **server/kanban_server/core/**

Anzi per essere più specifici modificherei anche kanban_server con semplicemente kanban, essendo sotto server è ovvio che si tratti del server del kanban.

**server/kanban_server/kanban_server/ -> server/kanban_server/core/ -> server/kanban/core/**

Molto più diretto e semplice da leggere.

**Comment by BugliL** [comment]
Questo Git era partito diverso ora e' diventato solo il server.
Django usa una sottocartella di base con scritto al suo interno lo stesso nome per fare lo scaffolding iniziale. Ovviamente i nomi si possono cambiare ma c'e' da fare attenzione che tutto continui a girare per bene, basta metterci le mani e modificare tutto a modo, mi stava molta fatica ed ho lasciato stare per il momento

Per essere puntigliosi cmq, il path giusto dovrebbe essere **/kanban/server/core** perche' il client dovrebbe essere **/kanban/client/angular/** e **/kanban/client/react/**
